export const APP_VERSION = '1.3.0';

export const themes = [
  { id: 'light', label: 'Light', description: 'Warm and calm' },
  { id: 'theme-biolum', label: 'Biolum', description: 'Deep sea bioluminescence' },
  { id: 'theme-radar-tactical', label: 'Tactical', description: 'Phosphor green radar' },
  { id: 'theme-steampunk', label: 'Steampunk', description: 'Brass, copper & amber' },
  { id: 'theme-crystal-depth', label: 'Crystal', description: 'Deep purple crystal' },
  { id: 'theme-midnight', label: 'Midnight', description: 'Deep blue serenity' },
  { id: 'theme-neon', label: 'Neon', description: 'Vibrant pink & purple' },
  { id: 'theme-green', label: 'Matrix', description: 'Terminal green code' },
  { id: 'theme-cyberpunk', label: 'Cyberpunk', description: 'High-tech yellow & blue' },
  { id: 'theme-glass', label: 'Glass', description: 'Pure & icy morphism' },
  { id: 'theme-sunset', label: 'Sunset', description: 'Warm gradients' },
  { id: 'theme-forest', label: 'Forest', description: 'Deep nature greens' },
  { id: 'theme-oled', label: 'OLED', description: 'True black power saver' },

  // New Themes
  { id: 'theme-mecca-night', label: 'Mecca Night', description: 'Black & Gold spiritual focus' },
  { id: 'theme-medina-rose', label: 'Medina Rose', description: 'Soft pink & green serenity' },
  { id: 'theme-blue-mosque', label: 'Blue Mosque', description: 'Iznik blue patterns' },
  { id: 'theme-desert-starlight', label: 'Starlight', description: 'Indigo deep desert night' },
  { id: 'theme-sahara-warmth', label: 'Sahara', description: 'Warm sand & orange' },
  { id: 'theme-andalusia-earth', label: 'Andalusia', description: 'Terracotta & emerald' },
  { id: 'theme-istanbul-sunset', label: 'Istanbul', description: 'Purple & orange silhouette' },
  { id: 'theme-taj-marble', label: 'Taj Marble', description: 'Minimalist white & stone' },
  { id: 'theme-royal-persian', label: 'Royal', description: 'Turquoise & gold leaf' },
  { id: 'theme-ramadan-lantern', label: 'Lantern', description: 'Cozy dark amber glow' },
] as const;

export const counterShapes = [
  { id: 'plain', label: 'Plain', icon: '◌' },
  { id: 'minimal', label: 'Minimal', icon: '○' },
  { id: 'classic', label: 'Classic', icon: '□' },
  { id: 'beads', label: 'Beads', icon: '◎' },
  { id: 'flower', label: 'Flower', icon: '❀' },
  { id: 'waveform', label: 'Wave', icon: '〰' },
  { id: 'digital', label: 'Digit', icon: '88' },
  { id: 'modern-ring', label: 'Ring', icon: '○' },
  { id: 'vintage-wood', label: 'Wood', icon: '▧' },
  { id: 'geometric-star', label: 'Star', icon: '۞' },
  { id: 'fluid', label: 'Fluid', icon: '≈' },
  { id: 'radar', label: 'Radar', icon: '⊕' },
  { id: 'real-beads', label: 'Real', icon: '📿' },
  { id: 'glass-orb', label: 'Glass', icon: '🔮' },
  { id: 'portal-depth', label: 'Portal', icon: '◎' },
  { id: 'luminous-ring', label: 'Lumi', icon: '✨' },
  { id: 'ring-light', label: 'Light', icon: '⭕' },
  { id: 'steampunk-nixie', label: 'Steam', icon: '⚙' },
  { id: 'biolum-organic', label: 'Bio', icon: '🧬' },
  { id: 'solar-flare', label: 'Solar', icon: '☀' },
  { id: 'nebula-cloud', label: 'Nebula', icon: '🌥' },
  { id: 'infinite-knot', label: 'Knot', icon: '➰' },
  { id: 'holo-fan', label: 'Fan', icon: '☄' },
  { id: 'halo-ring', label: 'Halo', icon: '💫' },
  { id: 'vertical-capsules', label: 'Capsule', icon: '💊' },
  { id: 'luminous-beads', label: 'LumiB', icon: '📿' },
  { id: 'animated-ripple', label: 'Ripple', icon: '◎' },
  { id: 'bead-ring', label: 'Bead Ring', icon: '📿' },
  { id: 'helix-strand', label: 'Helix', icon: '🧬' },
  { id: 'cyber-hexagon', label: 'Hex', icon: '⬡' },
  { id: 'blooming-lotus', label: 'Lotus', icon: '🌸' },
  { id: 'constellation', label: 'Stars', icon: '🌌' },
  { id: 'glass-pill', label: 'iOS Glass', icon: '🔮' },
  { id: 'emerald-loop', label: 'Emerald', icon: '🕋' },
  { id: 'smart-ring', label: 'Smart Ring', icon: '⌚' },

  // New Shapes
  { id: 'moon-phase', label: 'Moon', icon: '🌙' },
  { id: 'water-ripple', label: 'Ripple', icon: '💧' },
  { id: 'sand-hourglass', label: 'Hourglass', icon: '⏳' },
  { id: 'lantern-fanous', label: 'Lantern', icon: '🏮' },
  { id: 'digital-watch', label: 'Watch', icon: '⌚' },
  { id: 'star-burst', label: 'Starburst', icon: '💥' },
  { id: 'crystal-prism', label: 'Prism', icon: '💎' },
  { id: 'galaxy', label: 'Galaxy', icon: '🌌' },
  { id: 'tally-clicker', label: 'Tally 3D', icon: '🖱️' },
  { id: 'cyber-3d', label: 'Cyber 3D', icon: '💎' },
  { id: 'crystal-iso', label: 'Crystal ISO', icon: '🕋' },
  { id: 'neumorph', label: 'Neumorph', icon: '☁' },
] as const;

export const dashboardLayouts = [
  { id: 'default', label: 'Default', icon: 'layout-dashboard' },
  { id: 'minimal', label: 'Minimal', icon: 'minimize' },
  { id: 'timeline', label: 'Timeline', icon: 'git-commit' },
  { id: 'hub', label: 'Hub', icon: 'boxes' },
  { id: 'zen', label: 'Zen', icon: 'wind' },
  { id: 'cosmic', label: 'Cosmic Space', icon: 'sparkles' },
  { id: 'nature', label: 'Nature', icon: 'leaf' },
  { id: 'futuristic', label: 'Futuristic', icon: 'cpu' },
  { id: 'rugged', label: 'Rugged', icon: 'mountain' },
  { id: 'liquid', label: 'Liquid', icon: 'droplet' },
  { id: 'glassmorphic', label: 'Glassmorphic', icon: 'layers' },
  { id: 'skeuomorphic', label: 'Skeuomorphic', icon: 'box' },
  { id: 'tactile', label: 'Tactile', icon: 'hand' },
  { id: 'origami', label: 'Origami', icon: 'hexagon' },
  { id: 'claymorphic', label: 'Claymorphic', icon: 'circle' },
  { id: 'neumorphic', label: 'Neumorphic', icon: 'cloud' },
  { id: 'geometric', label: 'Geometric', icon: 'triangle' },
  { id: 'pop-art', label: 'Pop Art', icon: 'palette' },
  { id: 'cyberpunk', label: 'Cyberpunk', icon: 'zap' },
  { id: 'embroidery', label: 'Embroidery', icon: 'scissors' },
  { id: 'dreamy', label: 'Dreamy', icon: 'moon' },
  { id: 'isometric', label: 'Isometric', icon: 'cuboid' },
] as const;
